"""Initial migration.

Revision ID: 09b0f89aac63
Revises: 
Create Date: 2020-11-28 19:58:38.501598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b0f89aac63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_name', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('subject', sa.String(length=10), nullable=True),
    sa.Column('class_teaching', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_num', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('grade', sa.String(length=2), nullable=True),
    sa.Column('class_num', sa.String(length=3), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('correct_list', sa.PickleType(), nullable=True),
    sa.Column('wrong_list', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('teacher')
    # ### end Alembic commands ###
